# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
      include:
      - '*' 

pool:
  vmImage: 'windows-2019'

variables:
  serviceBusConnection: 'serviceBusConnection'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore NuGet Packages
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: Build All
  inputs:
    command: build
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: Publish Azure Function
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/CryptoCrawler.AzureFunc.csproj'
    arguments: '--no-restore --configuration Release --output $(Build.ArtifactStagingDirectory)'
- task: DotNetCoreCLI@2
  displayName: Pack Contracts
  inputs:
    command: 'pack'
    packagesToPack: '**/CryptoCrawler.Contracts.csproj'
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    publishVstsFeed: 'crypto_predictor_nuget'
    allowPackageConflicts: true
- task: PublishBuildArtifacts@1
  displayName: Generate Artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'artifacts'
    publishLocation: 'Container'
- task: PublishBuildArtifacts@1
  displayName: Generate ARM Templates
  inputs:
    PathtoPublish: 'ARMTemplates'
    ArtifactName: 'artifacts'
    publishLocation: 'Container'
