# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    architecture: 'x64'
    
- script: |
    python -m pip install --upgrade pip setuptools wheel
    python -m pip install --upgrade pip
    python -m pip install -r requirements.txt
  displayName: 'Install tools and requirements'
